version: "3"
services:
  todoservice:
    # container_name: todoName
    build: .
    image: andrewcbuensalida/todo:1.0
    environment:
      - PORT=6000
      - DBPW_TODO=${DBPW_TODO}
    ports:
      - "6000:6000"
    command: node script.js
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /tododb:/data/db
volumes:
  tododb:
