version: "3"
services:
  #   nginx:
  #     image: nginx:stable-alpine
  #     ports:
  #       - "80:80"
  #     volumes:
  #       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  # todoservice:
  #     container_name: todoName
  #     build: .
  #     image: node-mongodb-todo_todoservice
  #     environment:
  #       - PORT=4000
  #       - TEST=from prod
  #     ports:
  #       - "4000:4000"
  command: node script.js
# deploy:
#   replicas: 8
#   restart_policy:
#     condition: any
#   update_config:
#     parallelism: 2
#     delay: 15s
