version: "3"
services:
  todoservice:
    container_name: todoName
    build: .
    image: andrewcbuensalida/todo:1.0
    environment:
      - PORT=3500
      - DBPW_TODO=${DBPW_TODO}
    ports:
      - "3500:3500"
    command: node script.js
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=andrewcbuensalida
      - MONGO_INITDB_ROOT_PASSWORD=${DBPW_TODO}
    volumes:
      - /tododb:/data/db
volumes:
  tododb:
