version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  todoservice:
    # container_name: todoName
    build: .
    image: andrewcbuensalida/todo:1.0
    environment:
      - PORT=4000
      - TEST=from default again and again
      - DBPASS=${DBPASS}
    # ports:
    #   - "4000:4000"
    command: node script.js
    # deploy:
    #   replicas: 5
    #   # restart_policy:
    #   #   condition: always
    #   update_config:
    #     parallelism: 2
    #     delay: 15s
